// Runs at Netlify build time (see netlify.toml). Reads the two secrets from
// Netlify environment variables and writes them into js/config.js, which the
// browser loads as a plain global. This keeps the API key out of git history
// while still letting a static site read a public Google Sheet client-side.
//
// The API key is visible to anyone who views source in the deployed site —
// that's expected for a browser-side Google API key. Restrict it in Google
// Cloud Console (HTTP referrer = your Netlify domain, API = Google Sheets API
// only) so it can't be reused elsewhere. See README.md.

const fs = require("fs");
const path = require("path");

const SHEET_ID = process.env.PANTAI_SHEET_ID || "REPLACE_WITH_SHEET_ID";
const SHEETS_API_KEY = process.env.GOOGLE_SHEETS_API_KEY || "REPLACE_WITH_API_KEY";

const contents = `// AUTO-GENERATED by build.js at deploy time. Do not edit directly —
// set PANTAI_SHEET_ID and GOOGLE_SHEETS_API_KEY in Netlify env vars instead.
window.DASHBOARD_CONFIG = {
  SHEET_ID: "${SHEET_ID}",
  SHEETS_API_KEY: "${SHEETS_API_KEY}",
};
`;

fs.writeFileSync(path.join(__dirname, "js", "config.js"), contents);

if (SHEET_ID.startsWith("REPLACE_") || SHEETS_API_KEY.startsWith("REPLACE_")) {
  console.warn(
    "\n[build.js] WARNING: PANTAI_SHEET_ID and/or GOOGLE_SHEETS_API_KEY are not set.\n" +
    "The deployed dashboard will show a configuration error until these are set\n" +
    "as environment variables in Netlify (Site settings -> Environment variables).\n"
  );
} else {
  console.log("[build.js] Wrote js/config.js with configured Sheet ID and API key.");
}
